# config/config.yaml
trading:
  symbol: "BTCUSDT"
  base_asset: "BTC"
  quote_asset: "USDT"
  position_size: 0.01
  max_position_size: 0.05
  stop_loss_pct: 2.0
  take_profit_pct: 3.0
  max_trades_per_day: 10
  min_volume: 100000
  cooldown_period: 300
  max_slippage: 0.1

risk:
  max_drawdown: 10.0
  risk_per_trade: 1.0
  leverage: 1
