# config/model_config.yaml
model:
  batch_size: 64
  gamma: 0.95
  epsilon_start: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  learning_rate: 0.001
  memory_size: 10000
  target_update_frequency: 100
  model_path: "models/dqn_model.pth"
